### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DevulderJeanPaul** [will-lumley/ColorPicker#8]
Hi,

It's great if you can remove the private state for  colorPickerViewController value

for use the colorPickerViewController on others button style !

Thanks,

//private var colorPickerViewController: ColorPickerViewController

**Comment by will-lumley** [comment]
Hey @DevulderJeanPaul - happy to take this into consideration, but could you please provide the reason as to why we'd lower the ACL from `private`?
